# ~/.config/starship.toml

# InsÃ¨re une ligne vide entre les commandes shell
add_newline = true

# --- Kubernetes ---
[kubernetes]
disabled = false
symbol = "â˜¸ "
style = "bold blue"
format = '[$symbol$context( \($namespace\))]($style) '

# --- Git ---
[git_branch]
symbol = "ğŸŒ± "
style = "bold green"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
style = "bold red"
format = '([${all_status}$ahead_behind]($style) )'

# --- System & Shell ---
[os]
disabled = false
style = "bold white"

[shell]
disabled = false
format = "[$indicator]($style) "
style = "cyan bold"

[username]
style_user = "white bold"
style_root = "black bold red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = true
format = "on [$hostname](bold yellow) "
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
style = "bold cyan"

[sudo]
style = "bold red"
symbol = "ğŸ§™ "
disabled = false

[memory_usage]
disabled = false
threshold = 75
symbol = "ğŸ§  "
style = "bold dimmed white"
format = "[$symbol${ram}( ${swap})]($style) "

[jobs]
symbol = "ğŸš¦ "
style = "bold blue"

[cmd_duration]
min_time = 2_000
format = "â±ï¸ [$duration]($style) "
style = "bold yellow"

[time]
disabled = false
format = '[$time]($style) '
time_format = "%R" # Heure:Minute (24h)
style = "bold dimmed white"

# --- Cloud & Infrastructure ---
[aws]
symbol = "â˜ï¸ AWS "
style = "bold orange"
format = 'on [$symbol($profile )(\($region\) )]($style)'

[azure]
symbol = "â˜ï¸ AZ "
style = "bold blue"
disabled = false
format = 'on [$symbol($subscription)]($style) '

[gcloud]
symbol = "â˜ï¸ GCP "
style = "bold yellow"
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
disabled = false

[terraform]
symbol = "ğŸ—ï¸ TF "
style = "bold purple"
format = 'via [$symbol$workspace]($style) '

# --- Containers & Orchestration ---
[helm]
symbol = "âˆ "
style = "bold white"
format = 'via [$symbol($version )]($style)'

[docker_context]
symbol = "ğŸ³ "
format = 'via [$symbol$context]($style) '

[container]
symbol = "ğŸ“¦ "
format = '[$symbol$name]($style) '

# --- Langages ---
[python]
symbol = "ğŸ "
style = "bold yellow"
format = 'via [$symbol($version )(\($virtualenv\) )]($style)'

[golang]
symbol = "ğŸ¹ "
style = "bold cyan"
format = 'via [$symbol($version )]($style)'
