# ~/.config/starship.toml

# InsÃ¨re une ligne vide entre les commandes shell
add_newline = true

# --- Kubernetes ---
[kubernetes]
disabled = false
symbol = "â˜¸ "
style = "bold blue"
format = '[$symbol$context( \($namespace\))]($style) '

# On peut masquer le contexte s'il est trop long ou gÃ©nÃ©rique
# [kubernetes.context_aliases]
# "arn:aws:eks:..." = "EKS-Prod"

# --- Git ---
[git_branch]
symbol = "ğŸŒ± "
style = "bold green"

[git_status]
style = "bold red"
format = '([$all_status$ahead_behind]($style) )'

# --- System ---
[username]
style_user = "white bold"
style_root = "black bold red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = true
format = "on [$hostname](bold yellow) "
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
style = "bold cyan"

# --- Cloud & Langages (ActivÃ©s uniquement si fichiers dÃ©tectÃ©s) ---
[aws]
symbol = "â˜ï¸  "
style = "bold orange"
disabled = false

[docker_context]
symbol = "ğŸ³ "

[python]
symbol = "ğŸ "
